$ANSIBLE_VAULT;1.1;AES256
38363332373661626137373665386130633662323939323861623935643534313634353463333362
3631656265633332313366613438306364313833383636350a333236303631343532393335313461
34616131653966663335303836626263323062653038313039346366633930313430313232663338
3131356639643066650a646535343665343862366166346637363838623038376265353665343834
6363
